### PR TITLE
Remove `--all-features` from build scripts

### PR DESCRIPTION
**Pull request by lann**
@dicej I wanted to get the flag out of `make test`, so I figured I'd just clean it up everywhere while I was at it.

@vdice Any good way to test release jobs?

### CODE REVIEW

**Comment by lann** [comment]
Will rebase after #546 merges.

**Comment by dicej** [comment]
> > @vdice Any good way to test release jobs?
> 
> Yes, merge this branch to `main` on your fork an push. This will trigger the action.

But make sure Settings->Actions->General->Workflow permissions is set to "Read and write permissions" on your fork first.

**Comment by lann** [comment]
Oh right it's public now :laughing:

**Comment by lann** [comment]
Release builds passed here: https://github.com/lann/spin/actions/runs/2469517288 (those builds test this PR along with #551 since release builds take so long)

**Comment by itowlson** [comment]
Should we keep the `--all-features` in the clippy and fmt stuff?  Just be more specific in the actual build?

**Comment by lann** [comment]
> Should we keep the `--all-features` in the clippy and fmt stuff? Just be more specific in the actual build?

I'm not sure. It isn't ideal to to have to build openssl just for clippy. Since that is currently the only feature I think the answer _today_ is "no", but if we do add more features the answer could change. It might be that even then the right solution would be to list relevant features explicitly.

**Comment by dicej** [comment]
I'd lean towards leaving `--all-features` in for clippy.  Clippy is just so valuable for code quality, and I don't want its warnings to start slipping past CI because we forgot to include a `--features` flag.

**Comment by lann** [comment]
Alright, `--all-features` returns for `cargo clippy`

**Comment by lann** [comment]
> BTW, do we really need to run `cargo clippy` separately for every platform in the matrix? Won't `--all-targets` cover everything if we only run it e.g. on Linux? Likewise for `cargo fmt`.

We don't for PR builds. `fmt` and `clippy` are guarded by `if: ${{ matrix.config.platformAgnosticChecks }}`, which is only set for the Linux job.

**Comment by lann** [comment]
> I don't know if spin even has platform-specific code

It doesn't today. There are nice crates that abstract platform differences for most things.

**Comment by dicej** [comment]
Now I'm wondering about `cargo test`.  I also don't want failing, feature-specific tests to slip by CI.  What do you think?

**Comment by lann** [comment]
We found a better approach.

**Pull request closed without merging**
