### PR TITLE
Use tracing appender to improve performance

### PR DESCRIPTION
**Pull request by calebschoepp**
Borrowing idea from [here](https://github.com/fermyon/ros/pull/4)

I ran some benchmarks against the default `rust-http` app before and after the changes.

### Before
```sh
$ bombardier localhost:3000
Bombarding http://localhost:3000 for 10s using 125 connection(s)
[==========================================================================================================] 10s
Done!
Statistics        Avg      Stdev        Max
  Reqs/sec     18513.31    1447.98   21170.52
  Latency        6.75ms     1.41ms    36.56ms
  HTTP codes:
    1xx - 0, 2xx - 185196, 3xx - 0, 4xx - 0, 5xx - 0
    others - 0
  Throughput:     3.46MB/s
```

### After

```sh
$  bombardier localhost:3000
Bombarding http://localhost:3000 for 10s using 125 connection(s)
[==========================================================================================================] 10s
Done!
Statistics        Avg      Stdev        Max
  Reqs/sec     21480.65    1998.23   24816.04
  Latency        5.83ms     1.93ms    81.97ms
  HTTP codes:
    1xx - 0, 2xx - 214305, 3xx - 0, 4xx - 0, 5xx - 0
    others - 0
  Throughput:     4.00MB/s
```

### Thoughts
We can see that there is a perf improvement, but I'm a bit confused as to why. Now that I think about it my test wasn't even producing any tracing (the thing this change is supposed to speed up) b/c I was doing `spin up` without `RUST_LOG`.

I'm curious if anyone has ideas why this created a speedup anyways.

### CODE REVIEW

**Comment by kate-goldenring** [comment]
@calebschoepp I'm curious about this too. Maybe shutdown is cleaner/faster with the guard

**Comment by calebschoepp** [comment]
> @calebschoepp I'm curious about this too. Maybe shutdown is cleaner/faster with the guard

Shutdown of Spin or do you mean cleanup of a Wasm instance? I don't see why Spin shutting down quicker would increase throughput.

**Comment by kate-goldenring** [comment]
> I don't see why Spin shutting down quicker would increase throughput.

Good point 🤷‍♀️

**Comment by calebschoepp** [comment]
Benchmarking with `RUST_LOG=info spin up`

### Before
```sh
$ Bombarding http://localhost:3000 for 10s using 125 connection(s)
[==========================================================================================================] 10s
Done!
Statistics        Avg      Stdev        Max
  Reqs/sec     17286.99    1759.51   20610.16
  Latency        7.23ms     1.71ms    53.75ms
  HTTP codes:
    1xx - 0, 2xx - 172968, 3xx - 0, 4xx - 0, 5xx - 0
    others - 0
  Throughput:     3.23MB/s
```
### After
```sh
$ bombardier localhost:3000
Bombarding http://localhost:3000 for 10s using 125 connection(s)
[==========================================================================================================] 10s
Done!
Statistics        Avg      Stdev        Max
  Reqs/sec     16292.78    1933.98   22082.56
  Latency        7.67ms     2.15ms    60.37ms
  HTTP codes:
    1xx - 0, 2xx - 163007, 3xx - 0, 4xx - 0, 5xx - 0
    others - 0
  Throughput:     3.04MB/s
```

### Thoughts

So it's worse after the change when tracing is on?! 🤷 I'm confused, if I can't come up with a reasonable explanation I'll probably just close this PR and leave it with the status quo.

**Comment by calebschoepp** [comment]
I don't have a clear path forward here so I'm closing the PR

**Pull request closed without merging**
