### PR TITLE
ref(deploy): update duplicate short flag

### LINKED ISSUE #582: spin deploy defines -d flag twice
```
../../target/debug/spin help deploy
thread 'main' panicked at 'Command deploy: Short option names must be unique for each argument, but '-d' is in use by both 'STAGING_DIR' and 'redeploy'', /home/bacongobbler/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.1.15/src/build/debug_asserts.rs:110:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

https://github.com/fermyon/spin/blob/93f109188ce1feec15328f5935ae16a8835843e2/src/commands/deploy.rs#L79

https://github.com/fermyon/spin/blob/main/src/commands/deploy.rs#L116

### PR DESCRIPTION
**Pull request by michelleN**
resolves #582 
Signed-off-by: Michelle Dhanani <michelle@fermyon.com>

### CODE REVIEW

**Review by vdice — APPROVED** [review]
We could also consider supplying only the long flag for this option.  LGTM regardless.

**Comment by bacongobbler** [comment]
With this change, I'm seeing this:

```
><> ../../target/debug/spin deploy --help
thread 'main' panicked at 'Command deploy: Argument or group 'buildinfo' specified in 'conflicts_with*' for 'no-buildinfo' does not exist', /home/bacongobbler/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.1.15/src/build/debug_asserts.rs:181:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This does fix the previous issue, but a new one came up as well.

**Comment by michelleN** [comment]
@bacongobbler so strange because I'm not seeing this error. Can you push up the branch you are using to test?

**Comment by bacongobbler** [comment]
pushed a fix in #584

**Pull request merged**
