### PR TITLE
Setup a docker compose file that creates an o11y stack for Spin to use

### PR DESCRIPTION
**Pull request by calebschoepp**
~This is still a WIP, but~ I'd love feedback on the config itself and on where we want to store this config.

### CODE REVIEW

**Comment by rylev** [comment]
Can you give me some more context on how you imagine these being used? My gut is that this should be in a different repo, but without knowing about how this will be used, it's hard to say.

**Comment by calebschoepp** [comment]
> Can you give me some more context on how you imagine these being used? My gut is that this should be in a different repo, but without knowing about how this will be used, it's hard to say.

I envision some using this to easily setup an observability stack for their spin app

```shell
cd o11y
docker compose up
# Now do my Spin things
```

We could potentially put this in another repo, or hide it behind a spin plugin, or somewhere else. But, I do think we need to provide a simple and coherent story for how users of Spin can get the very wide set of o11y tools running easily.

**Comment by itowlson** [comment]
Is this solving a Spin-specific observability issue or a "generic observability tools setup" issue?  That might help guide the discussion.

**Comment by lann** [comment]
I don't have a strong opinion about what repo this should live in, but _if_ it's going to be in this repo I would like to put it in e.g. `contrib/o11y-stack` (or `hack/...`, as the k8s ecosystem seems to like) to indicate that it isn't _necessarily_ an actively-supported feature of Spin itself.

As an aside I think `tools/modsurfer` should be moved for the same reason.

**Comment by calebschoepp** [comment]
I like the pattern of `hack/o11y-stack/*`.

**Comment by calebschoepp** [comment]
> Is this solving a Spin-specific observability issue or a "generic observability tools setup" issue? That might help guide the discussion.

Good framing question @itowlson. There is nothing inherently specific to Spin here so I would say this is a "generic observability tools setup" issue.

**Comment by calebschoepp** [comment]
I've moved it to `hack/o11y-stack/`. Looking for another round of reviews on if we're okay storing it there.

**Review by lann — APPROVED** [review]
The great thing about `hack/*` is that we can just delete it later :slightly_smiling_face:

**Pull request merged**
