### PR TITLE
Backport script

### PR DESCRIPTION
**Pull request by lann**
Also revert the workflow that doesn't work.

Usage:

`.github/gh-backport.sh <PR #> <branch>`

e.g.

```console
$ .github/gh-backport.sh 1274 v1.0
Switched to a new branch 'backport-1274-to-v1.0'
Cherry picking commits...
[backport-1274-to-v1.0 b7c5007] fix wagi redirect status code
 Author: Rajat Jindal <rajatjindal83@gmail.com>
 Date: Wed Mar 15 23:09:39 2023 +0530
 1 file changed, 15 insertions(+), 8 deletions(-)
? Where should we push the 'backport-1274-to-v1.0' branch? lann/spin

Creating pull request for lann:backport-1274-to-v1.0 into main in fermyon/spin

remote: 
remote: 
To github.com:lann/spin.git
 * [new branch]      HEAD -> backport-1274-to-v1.0
branch 'backport-1274-to-v1.0' set up to track 'pub/backport-1274-to-v1.0'.
https://github.com/fermyon/spin/pull/1281
```

(which created #1281)

### CODE REVIEW

**Review by itowlson — APPROVED** [review]

**Review by vdice — COMMENTED** [review]
This worked well for me (https://github.com/fermyon/spin/pull/1284)!  Though, I needed to do some setup (as a first time `gh`-user).  Wonder if any/all of these should go in as script comments or a doc somewhere?

I needed:
-  `gh auth login`
- `gh repo set-default fermyon/spin`
- and I selected 'Create a fork of fermyon/spin' as the answer to the `? Where should we push the 'backport-1269-to-v1.0' branch?` question (somewhat unintuitively; I already had a fork and indeed it just used vdice/spin).

**Comment by lann** [comment]
Yeah, this is definitely Minimum Viable Script here. I might turn it into a gh extension which I just learned exists: https://cli.github.com/manual/gh_extension

**Comment by itowlson** [comment]
Oh, I didn't realise it depended on the user setting a default repo.  (I didn't even know default repo was a thing.)  Can't we just script it to use the Spin repo?

**Comment by rajatjindal** [comment]
can we use this script from within the Github actions? e.g. a workflow that run this script on a specific comment on the PR?

**Pull request merged**
