### PR TITLE
docs(deploy): add spin deploy doc

### PR DESCRIPTION
**Pull request by michelleN**
Signed-off-by: Michelle Dhanani <michelle@fermyon.com>

### CODE REVIEW

**Review by radu-matei — APPROVED** [review]
Yaay, thanks!

One comment around the date for the article, but otherwise LGTM.

**Comment by radu-matei** [comment]
Also, do we want to link this from a page on the sidebar, or not yet?

**Comment by michelleN** [comment]
@radu-matei - just added the date

> Also, do we want to link this from a page on the sidebar, or not yet?

yeah, I think that makes sense. Should I add it under "Using Spin" or "Advanced"? I'm leaning towards "Advanced".

**Comment by radu-matei** [comment]
Advanced sounds good.
Thanks!

**Pull request merged**
