### PR TITLE
Update template to use PHP 8.2

### PR DESCRIPTION
**Pull request by technosophos**
I updated PHP from version 7 to version 8.2 (VMware has made some MAJOR progress).

### CODE REVIEW

**Comment by technosophos** [comment]
Ah! I see the smoke test requires an update. Fixing

**Review by itowlson — APPROVED** [review]

**Comment by technosophos** [comment]
I'm struggling to figure out the error from the output in GH actions:
```
test integration_tests::http_php_template_smoke_test ... ok
Error: 'cd "/tmp/t56c8-8" && CARGO_TARGET_DIR="/tmp/t56c8-8/target" PATH="target/debug:target/release:/home/runner/.cargo/bin:/home/runner/work/spin/spin:/home/runner/work/spin/spin/swift-wasm-5.8-SNAPSHOT-2023-02-24-a/usr/bin:/opt/hostedtoolcache/node/16.20.2/x64/bin:/opt/hostedtoolcache/binaryen/116/x86_64/binaryen-version_116/bin:/opt/hostedtoolcache/tinygo/0.27.0/amd64/tinygo/bin:/home/runner/go/bin:/opt/hostedtoolcache/go/1.20.1/x64/bin:/opt/hostedtoolcache/zig/master/x64:/snap/bin:/home/runner/.local/bin:/opt/pipx_bin:/home/runner/.cargo/bin:/home/runner/.config/composer/vendor/bin:/usr/local/.ghcup/bin:/home/runner/.dotnet/tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/runner/work/spin/spin/target/release" "/home/runner/work/spin/spin/target/release/spin" "build"' failed with status code Some(1)
test integration_tests::http_python_template_smoke_test ... FAILED
stdout:
Building component test with `componentize-py -w spin-http componentize -p . -p $(python3 -c 'import site; print(site.getsitepackages()[0])') app -o app.wasm`

stderr:
sh: 1: componentize-py: not found
Error: Build command for component test failed with status Exited(127)

```

Is there a way to run just that part of the test locally so I can see if I can debug it?

**Comment by itowlson** [comment]
That sounds like overlapped output from the Python and PHP tests?  @karthik2804 is in the middle of updating the Python test - it needed to be synced with the update the to Python SDK.  Hopefully wait a few moments and it will be fixed.  If this is urgent then we can try to figure something out.

**Comment by itowlson** [comment]
Looking at the action output, the Python test is the only one failing and we know why that is, so we can force merge this if any friendly admins are around.

**Comment by technosophos** [comment]
Okay. No urgent need to merge it. I was working with @rawkode to get a PHP demo together, but IIRC he is already testing this on his own.

**Comment by karthik2804** [comment]
This needs a rebase I think.

**Pull request merged**
