### PR TITLE
ref(telemetry): Provide the abililty to turn off the tracing-log compat layer in tracing-subscriber dep of telemetry

### PR DESCRIPTION
**Pull request by calebschoepp**

### CODE REVIEW

**Comment by calebschoepp** [comment]
I tested to make sure that `tracing::log::*` is still being picked up in the main Spin binary. This is ready for review.

**Comment by lann** [comment]
What is the goal with this compat layer?

**Comment by radu-matei** [comment]
ref https://github.com/spinkube/containerd-shim-spin/pull/112

**Comment by calebschoepp** [comment]
> What is the goal with this compat layer?

@lann the goal of the compat layer is to keep the [`tracing-log` feature](https://docs.rs/tracing-subscriber/0.3.18/tracing_subscriber/#optional-dependencies) turned on when Spin is compiled as a standalone binary. This is so that we can still pick up any `log::*` emitted by upstream libraries. For example wasmparser uses `log::*` and not `tracing::*`.

**Review by lann — APPROVED** [review]

**Pull request merged**
