### PR TITLE
Unbindle the `up` command and app manifest

### PR DESCRIPTION
**Pull request by itowlson**
okay let's see what blows up in CI

### CODE REVIEW

**Comment by itowlson** [comment]
I have removed integration tests that depended on `spin up --bindle`.  These related to bindle round-tripping and are probably okay to get rid of.  However this does potentially undermine our test coverage for Cloud; if something goes wrong with the bindle push logic, these tests will no longer catch it.  Are we okay with that as the price for removing the bindle flags now?

There is an integration test `test_headers_env_routes` which is failing.  It currently relies on Bindle, but I am not sure what it is aiming to test or why Bindle is in the loop for it, so am reluctant to remove it.  Any ideas folks?

**Comment by radu-matei** [comment]
cc @rajatjindal as to whether we could use the Cloud end to end test to make sure we don't undermine testing there.

**Comment by radu-matei** [comment]
Re: the `test_headers_env_routes` test, it's probably the first end to end test that I wrote as part of the really early suite.
The rest of the tests should capture anything tested there, so we should be ok removing it.

**Comment by rajatjindal** [comment]
> cc @rajatjindal as to whether we could use the Cloud end to end test to make sure we don't undermine testing there.

There was a plan to cover these tests as part of `Fermyon Platform` e2e tests, but with Bindle flags getting deprecated/removed, I don't see a lot of value in having these tests (assuming Fermyon Platform will also make use of OCI registry instead of Bindle in future).

`e2e-tests` currently deploy to Cloud, which uses Bindle behind the scenes. So we have some coverage but not specifically for the "spin bindle push".

**Comment by rajatjindal** [comment]
> 


This test covers two scenarios:

1. environment variables are read from `spin.toml`.
2. env variables passed using `--env` during `spin-up`.

We have coverage for the first scenario for `spin up` and `Fermyon Cloud`. But for the second scenario, we have the test coverage on `spin up` only, as it is not supported on the Cloud yet.

**Comment by itowlson** [comment]
Great stuff, thank you @radu-matei and @rajatjindal

**Review by lann — APPROVED** [review]

**Review by fibonacci1729 — APPROVED** [review]

**Pull request merged**
