### PR TITLE
feat(sdk/go): implement mysql SDK for TinyGo

### PR DESCRIPTION
**Pull request by Patrick0308**
feat(sdk/go): implement mysql SDK for TinyGo

### CODE REVIEW

**Comment by Patrick0308** [comment]
Test `spin build` error. See:
```
Building component tinygo-mysql with `tinygo build -target=wasi -gc=leaking -o main.wasm main.go`
# github.com/fermyon/spin/sdk/go/mysql
../../../../../../opt/homebrew/Cellar/tinygo/0.30.0/lib/clang/include/stdbool.h:20:14: undefined: C._Bool
Error: Build command for component tinygo-mysql failed with status Exited(1)
```
I create a issue on Tinygo https://github.com/tinygo-org/tinygo/issues/3926 .

**Comment by itowlson** [comment]
Thanks for this, and for flagging the upstream problem to the TinyGo folks - looks like they already have a fix so hopefully in the next version...

**Comment by Patrick0308** [comment]
@adamreese PTAL

**Review by adamreese — COMMENTED** [review]
Looks great! I tested out on TinyGo dev. We need to wait to merge until the `C._Bool` issue is released in TinyGo.

**Comment by itowlson** [comment]
@Patrick0308 I _think_ a rebase will take care of the weird wit-bindgen compilation errors in CI.  Thanks for sticking with this!

**Comment by Patrick0308** [comment]
@adamreese @itowlson I replaced C._Bool to bool then testing the program went smoothly. So we don't need to wait util https://github.com/tinygo-org/tinygo/issues/3926  is released.

**Review by adamreese — APPROVED** [review]
Thanks for your great work on this feature!  This is awesome

**Pull request merged**
