### PR TITLE
chore: update clap dependency to 4.1

### PR DESCRIPTION
**Pull request by cardoso**
I kept changes to a minimum this time, so there's redundant parameters or with better alternatives in v4, but those should be easy to improve as needed. The display order in help was also kept the same by overriding the new default in each Subcommand.

### CODE REVIEW

**Comment by vdice** [comment]
Thanks @cardoso, appreciate how this brings the `clap` update but in perhaps a more staged approach so that usage can be further updated (and more recent functionality/features utilized) in follow-ups.

Glancing through the changes, all looks well; however, the e2e tests are catching similar breaking CLI behavior as seen in https://github.com/fermyon/spin/pull/1053#pullrequestreview-1272757152.  Do you think it should be fairly straightforward to address these (eg retain current CLI behavior) and still land the dependency updates?

**Comment by cardoso** [comment]
It's not possible with clap 4. It really wants unknown args to be either after -- or next to each outer,  so it assumes anything after an unknown arg is also unknown. I'm pushing a sample workaround to see what the tests say...

**Comment by cardoso** [comment]
REF: https://github.com/clap-rs/clap/issues/1404#issuecomment-1342502698

**Comment by cardoso** [comment]
I will close this one as blocked by https://github.com/clap-rs/clap/issues/1404 or alternatively, once the breaking change can be made to the to the more conventional `spin up [args] -- [trigger args]`.

I think I reached a solution at some point, but it involved refactoring a lot of code that's receiving constant changes. Suffice to say...

image

**Comment by itowlson** [comment]
Thank you @cardoso for all your effort on this - I'm sorry it didn't work out.  This definitely seems to be a regression between clap 3 and clap 4, but looking at that issue it seems to be 'by design.'  Frustrating!

**Pull request closed without merging**
