### PR TITLE
feat: show when there are no build commands in spin.toml

### PR DESCRIPTION
**Pull request by jim4067**
Signed-off-by: Jimii <jimmyimpulse2@gmail.com>

ref #700 and #703

### CODE REVIEW

**Review by itowlson — APPROVED** [review]
Looks good to me - thanks!

**Review by radu-matei — APPROVED** [review]
Thank you for your contribution and for your patience!

This looks good to me!

**Comment by radu-matei** [comment]
@jim4067 — final thing before merging — could you please add a GPG signature to your commit?
https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification

Thanks!

**Comment by jim4067** [comment]
Thanks. Always wondered what verified means.

**Pull request merged**
