### PR TITLE
For errors, gently suggest rustup check

### LINKED ISSUE #783: Note which Rust versions are supported
FWIW, I followed the directions for at [Taking Spin for a spin \| Spin Documentation](https://spin.fermyon.dev/quickstart) and got this error:

```
$ spin build
...
   Compiling wit-bindgen-gen-rust v0.2.0 (https://github.com/bytecodealliance/wit-bindgen?rev=cb871cfa1ee460b51eb1d144b175b9aab9c50aba#cb871cfa)
error: there is no argument named `n`
   --> /home/neal/.cargo/git/checkouts/wit-bindgen-f98ccff846621481/cb871cf/crates/gen-rust/src/lib.rs:480:39
    |
480 |                         write!(name, "{n}").unwrap();
    |                                       ^^^

error: there is no argument named `name`
   --> /home/neal/.cargo/git/checkouts/wit-bindgen-f98ccff846621481/cb871cf/crates/gen-rust/src/lib.rs:621:46
    |
621 |             self.push_str(&format!("pub enum {name}"));
    |                                              ^^^^^^

error[E0658]: use of unstable library feature 'iter_zip'
 --> /home/neal/.cargo/git/checkouts/wit-bindgen-f98ccff846621481/cb871cf/crates/gen-rust/src/lib.rs:4:5
  |
4 | use std::iter::zip;
  |     ^^^^^^^^^^^^^^
  |
  = note: see issue #83574 <https://github.com/rust-lang/rust/issues/83574> for more information

error[E0658]: use of unstable library feature 'iter_zip'
   --> /home/neal/.cargo/git/checkouts/wit-bindgen-f98ccff846621481/cb871cf/crates/gen-rust/src/lib.rs:595:13
    |
595 |             zip(self.union_case_names(iface, union), &union.cases)
    |             ^^^
    |
    = note: see issue #83574 <https://github.com/rust-lang/rust/issues/83574> for more information

For more information about this error, try `rustc --explain E0658`.
error: could not compile `wit-bindgen-gen-rust` due to 4 previous errors
warning: build failed, waiting for other jobs to finish...
error: build failed
Error: Build command for component spin-hello-world failed with status Exited(101).

```

I checked for a Rust update:
```
$ rustup check
stable-x86_64-unknown-linux-gnu - Update available : 1.57.0 (f1edd0429 2021-11-29) -> 1.64.0 (a55dd71d5 2022-09-19)
rustup - Update available : 1.24.3 -> 1.25.1
```

and did a `rustup update` to upgrade. Then the build went smoothly, and it ran like a champ. [Cool!]

So I suggest adding a note to the quickstart documenting a working version of the Rust toolchain, or at least suggesting a check.

### PR DESCRIPTION
**Pull request by nealmcb**
Fixes #783

Signed-off-by: Neal McBurnett <nealmcb@gmail.com>

### CODE REVIEW

**Review by itowlson — CHANGES_REQUESTED** [review]
Great catch - thanks!  I reckon we should also mention this on the Rust page: https://github.com/fermyon/spin/blob/main/docs/content/rust-components.md - otherwise all grand.

We should have a think about how to ensure the versioning information remains correct.   Maybe pin CI to a specific Rust version and add a check that the docs match CI.  (That's definitely out of scope for this PR!  I'm just thinking out loud.)

**Review by itowlson — APPROVED** [review]
Looks good - thanks!

**Comment by nealmcb** [comment]
Thanks, @itowlson. I clarified the [rust-components.md](https://github.com/fermyon/spin/blob/main/docs/content/rust-components.md) page a bit. I note they already mentioned Rust versioning, and they mention 1.56+ which is actually older than what i was running.

Given that this project is moving quickly, we could just remove the specific version number recommendations and suggest getting a "recent" version.

**Comment by itowlson** [comment]
We could, though I quite like the specific minimum, as it avoids ambiguity.  As the one who got bitten by the issue, do you think "check for a recent version" would have helped enough, or would you have preferred "check for 1.56+"?

**Comment by nealmcb** [comment]
I think just mentioning that rust versions are something to check is fine. I doubt that maintainers of the code base will enjoy trying to keep recommendations for specific person numbering up to date, until there's a 1.0 release.

**Comment by itowlson** [comment]
> I doubt that maintainers of the code base will enjoy trying to keep recommendations for specific version numbering up to date

_can confirm_  **grin**

So on that basis, would you like us to merge this PR as it stands, or to reword, or to close this one and have us pick it up?

**Comment by nealmcb** [comment]
I dare say that this, without the version numbers, is best for now.

**Review by itowlson — APPROVED** [review]
Yes, I like that - specific action but low-maintenance - thanks for the careful thought on this.  Looks good to me; is it okay to merge?

**Comment by nealmcb** [comment]
Go for it. Thanks!

**Pull request merged**
