### PR TITLE
remove `Send` and `Sync` bounds from Rust SDK router

### PR DESCRIPTION
**Pull request by dicej**
These bounds were preventing users from calling async functions which use `http::executor` since it uses `Rc<RefCell<_>>` internally, which is neither `Send` nor `Sync`.

See https://discord.com/channels/926888690310053918/1187255600002891798 for details.

### CODE REVIEW

**Review by rylev — APPROVED** [review]

**Comment by seungjin** [comment]
I still got the same error with 
```
# spin --version
spin 2.2.0-pre0 (a1a82c9c 2023-12-22)
```
I build from source now. So my spin has this merge in.

**Comment by dicej** [comment]
@seungjin The version of Spin you use doesn't matter in this case -- it's the spin_sdk version that matters.  Would you please double-check that you're using a version of spin_sdk that contains this fix?

**Comment by seungjin** [comment]
In my Cargo.toml 
```
spin-sdk = { git = "https://github.com/fermyon/spin", branch = "main" }
```

Did `cargo clean`, `spin build`

**Comment by seungjin** [comment]
Did with (in my Cargo.toml)
```
spin-sdk = { git = "https://github.com/fermyon/spin", rev = "10ec302282896cdbc2860fc8beaebba7c01c72af" }
```
and compile was succeeded!!

**Comment by seungjin** [comment]
Isn't the code in the main branch??
Not working with branch = main but works with rev = "10ec30228...." ?

**Comment by dicej** [comment]
The main branch has it.  You may need to run `cargo update` to force cargo to fetch the latest code and update your Cargo.lock file.

**Comment by seungjin** [comment]
Yep. Figured out it is lock file. Working back now. 
Thanks for fixing this issue!!!

**Comment by seungjin** [comment]
Compile was succeed and I deploied and tested. 
But I don't get actually outbound http request's response to print.

**Comment by seungjin** [comment]
Never mind.. Working.. had two spin running.. some indirection happened.

**Pull request merged**
