### PR TITLE
Templates for Manifest v2 and SDK v2

### PR DESCRIPTION
**Pull request by itowlson**
This is a work in progress!  I'm putting it up so people can advise on the best way to show HTTP responses, bikeshed the template TOML, kick the tyres, etc.

### CODE REVIEW

**Comment by itowlson** [comment]
I would like to merge this if the unit tests pass, despite it being only partial (and despite the e2e failure), to see if it unblocks e2e.  The trouble we have is that e2e is using the templates from main not from the PR being tested, so I can't confirm that the changes here fully fix e2e without merging them.

**Comment by itowlson** [comment]
Although I am concerned that e2e is reporting Go and "registry" errors too.

**Comment by itowlson** [comment]
Ah... those need to run `go mod tidy`

**Comment by itowlson** [comment]
I have naughtily rolled a candidate fix for the other e2e tests into this PR.  Your forgiveness is requested.

**Review by lann — APPROVED** [review]

**Pull request merged**
