### PR TITLE
bump to hippo-cli 0.15

### LINKED ISSUE #603: update hippo health check in spin deploy
update hippo health check in spin deploy to reflect that now the /healthz endpoint will return 503 if not healthy.
https://github.com/fermyon/spin/pull/594#issuecomment-1167536733

### PR DESCRIPTION
**Pull request by bacongobbler**
This makes spin compatible with Hippo v0.19.0.

closes #603

### CODE REVIEW

**Review by radu-matei — COMMENTED** [review]
I manually tested this locally and things look good to me.

This now requires a bit of work to rebase (ref #681, cc @kate-goldenring).

Thanks!

**Comment by kate-goldenring** [comment]
> This now requires a bit of work to rebase (ref #681, cc @kate-goldenring).

@radu-matei and @vdice just use GitHub UI to fix the merge conflicts. Should be good.

**Review by vdice — APPROVED** [review]
Tested in conjunction with https://github.com/fermyon/installer/pull/97; LGTM

**Comment by vdice** [comment]
@kate-goldenring does the recently updated spin deploy logic need some fixups for hippo-0.19 compatibility?

**Comment by kate-goldenring** [comment]
> @kate-goldenring does the recently updated spin deploy logic need some fixups for hippo-0.19 compatibility?

Good point @vdice. Looks like I really merged these in the wrong order. I'll look into it.

**Comment by radu-matei** [comment]
Added in #697.
Thanks!

**Pull request closed without merging**
