### PR TITLE
Update rdbms-types to support Date / Tmestamp

### PR DESCRIPTION
**Pull request by tyler-harpool**
Purpose of this PR is to add datetime and timestamp support.

### CODE REVIEW

**Review by rylev — CHANGES_REQUESTED** [review]
Thanks for the PR! Adding this will constitute a breaking change so we'll need to make sure we do accept this at the right time. We're figuring out what changes to land in Spin 3.0 so this will definitely be a good candidate for discussion. In the meantime, we appreciate your patience while the discussion happens.

**Comment by itowlson** [comment]
Note this will also require updating the conversion routines in the MySQL and Postgres factors.

**Comment by tyler-harpool** [comment]
Would love to handle this, but bandwidth is limited as I'm on holiday/PTO. I'm happy to punt as this would be a challenge on my side. Happy to do anything to assist.

**Comment by itowlson** [comment]
I'm closing this in favour of #2890 - @tyler-harpool is aware.  Thank you again Tyler for getting this process under way!

**Pull request closed without merging**
