### PR TITLE
Exercise `spin up --key-value` in tests

### PR DESCRIPTION
**Pull request by itowlson**
Main question is whether this should be covered in the existing KV test (as is done here) or broken out into a separate test.

(It would also be nice to generate a random init pair but at the moment it is a bit painful to tell the guest module what the random values are.)

### CODE REVIEW

**Comment by rajatjindal** [comment]
having it in same test is fine, but we just need to ensure that the key/value pair is random to avoid false negatives

one of the thing we do currently in this test is to do the kv operations with in `lib.rs`. what we could do instead is to have those operations triggered by calling the http endpoint. 

so we can do things like

```
key=`random key`
value=`random value`

spin up --key-value $key=$value
actual_value=curl http://localhost:3000/get?key=$key
assert $value == $actual_value
```

I do this in some synthetic monitors that we have and it seems to work just fine.

**Comment by itowlson** [comment]
@rajatjindal That sounds good but I can't figure how to do it without significant surgery.  The issue is getting the dynamically generated random strings into the URL, because the URL is hardwired into the `checks` function.  If I try to pass the values in via  the call the `checks`, it fails because `assertions` requires an actual `fn` rather than a closure (i.e. cannot capture the variables from the outer scope).  And I can't pass the values as arguments to the `assertions` lambda, because that has to conform to `ChecksFunc` which has no scope for custom data.

I could change the definition of ChecksFunc, but that's used widely.  Or have an alternative `assertions_extra` of a function type that accepts extra data, but not sure how that would pan out as you need to have exactly one.

I'll continue to noodle but if you have any thoughts then I'd be glad of the advice!

**Comment by rajatjindal** [comment]
could we do something like:

```
 let key = "some-random-key";
 env::set_var("KV_TEST_INIT_KEY", key.to_string());
```

and then

```
async fn checks(
            metadata: AppMetadata,
            // TODO: investigate why omitting these two next parameters does not
            // cause a compile time error but causes a runtime one
            _: Option<BufReader<ChildStdout>>,
            _: Option<BufReader<ChildStderr>>,
        ) -> Result<()> {
            println!(
                "random key is {}",
                env::var("KV_TEST_INIT_KEY").unwrap_or("".to_string())
            );
            assert_http_response(
```

but it won't work if we try to reuse the `testcase` (may still work if we reuse `test app`).

Rajat 🏃‍♂️ and  hide.

**Comment by itowlson** [comment]
@rajatjindal Oh, sorry, I forgot to update!  I found a way to let `assertions` accept a closure and _with a bit of bonus cloning_ it seems to work now.  So it is ready for re-review.

**Review by kate-goldenring — APPROVED** [review]
Love the way you are passing the expected key and value through a url query! This is slick!

**Comment by itowlson** [comment]
@kate-goldenring That was entirely @rajatjindal's idea so all the credit is to him!  I agree it is nifty!

**Comment by rajatjindal** [comment]
thank you for fixing this @itowlson

**Pull request merged**
