### PR TITLE
Bump versions for v2.7 release

### PR DESCRIPTION
**Pull request by me-diru**
related to #2690

### CODE REVIEW

**Review by vdice — COMMENTED** [review]
For the version bumps on main, we'd want to bump to the prerelease for the next anticipated release.  In this case, `v2.8.0-pre0`.

**Comment by me-diru** [comment]
thanks! Should we go for `v3.0.0-pre0` instead, as we are expecting Spin `3.0` as our next release.

**Comment by itowlson** [comment]
I would avoid making the assumption that 3.0 will be next.  I'd stick to 2.8-pre for now, and rev to 3.0 once we commit to "counting down to 3.0".

**Comment by itowlson** [comment]
Basically rev to 3.0-pre once we start landing breaking changes.  Unless we expect to start doing so near-immediately, in which case :shipit:

**Comment by me-diru** [comment]
I think we already wanted to go for 3.0 after 2.6, however, 2.7 was the last anticipated version. I think spin-factors and other work will lead to breaking changes that will require a major release of `3.0`. @lann might give better input on that end.

**Pull request closed without merging**
