### PR TITLE
Check for `wasm32-wasi` target in build script

### PR DESCRIPTION
**Pull request by GeorgeHahn**
Display a helpful error if the `wasm32-wasi` target is not installed.

Windows:

```
PS> cargo build
   Compiling spin-cli v0.1.0 (C:\Users\George\code\spin)
   Compiling spin-publish v0.1.0 (C:\Users\George\code\spin\crates\publish)
   Compiling spin-build v0.1.0 (C:\Users\George\code\spin\crates\build)
   Compiling spin-http-engine v0.1.0 (C:\Users\George\code\spin\crates\http)
error: failed to run custom build command for `spin-cli v0.1.0 (C:\Users\George\code\spin)`

Caused by:
  process didn't exit successfully: `C:\Users\George\code\spin\target\debug\build\spin-cli-d04fca240bd81048\build-script-build` (exit code: 1)
  --- stdout
  cargo:rerun-if-changed=build.rs

  error: the `wasm32-wasi` target is not installed
      = help: consider downloading the target with `rustup target add wasm32-wasi`
warning: build failed, waiting for other jobs to finish...
error: build failed
```

Linux:

```
$ cargo build
   Compiling cranelift-wasm v0.81.1
   Compiling reqwest v0.11.10
   Compiling spin-cli v0.1.0 (/home/george/spin)
error: failed to run custom build command for `spin-cli v0.1.0 (/home/george/spin)`

Caused by:
  process didn't exit successfully: `/home/george/spin/target/debug/build/spin-cli-a73a64dd7920bc93/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-changed=build.rs

  error: the `wasm32-wasi` target is not installed
      = help: consider downloading the target with `rustup target add wasm32-wasi`
warning: build failed, waiting for other jobs to finish...
error: build failed
```

Toolchain overrides are handled correctly. `rustup target list --installed` automatically selects the correct version based on the `RUSTUP_TOOLCHAIN` environment variable. The error's help message is corrected when building on a non-default toolchain.

```
PS> cargo +nightly build
...
  error: the `wasm32-wasi` target is not installed
      = help: consider downloading the target with `rustup +nightly target add wasm32-wasi`
```

Closes https://github.com/fermyon/spin/issues/139

### CODE REVIEW

**Review by itowlson — APPROVED** [review]
LGTM - thanks for making this easier to diagnose!

**Comment by itowlson** [comment]
Could you sign the commit and re-push please?  (There's a minor clippy lint as well.)  Thanks!

**Comment by GeorgeHahn** [comment]
@itowlson ✔

**Review by radu-matei — APPROVED** [review]
Oh, this is great!
Thank you so much for fixing this, @GeorgeHahn!

LGTM

**Comment by GeorgeHahn** [comment]
Thanks for the quick reviews & merge!

**Pull request merged**
