### PR TITLE
[sdk]: Add options fn on HTTP router for Rust

### PR DESCRIPTION
**Pull request by ThorstenHans**
This PR adds the `options` method for the `Router` struct provided by Spin SDK for Rust.

This allows users to quickly register handlers for incoming requests using the `OPTIONS` method:

## Usage example

```rust
fn handle_options(_r: Request, _params: Params) -> Result<Response> {
  Ok(http::Response::builder().status(http::StatusCode::OK).body(None)?)
}

#[http_component]
fn handle_foo(req: Request) -> Result<Response> {
  let mut router = Router::default();
  router.options("/foo", handle_options);
  router.handle(req)
}
```

### CODE REVIEW

**Comment by fibonacci1729** [comment]
Thank you @ThorstenHans, looks great! Would you mind updating the `http_router` macro as well to keep the experiences consistent? I.e.

```
     ...
    (@build $r:ident OPTIONS $path:literal => $h:expr) => {
        $r.options($path, $h);
    };
    ...
```

**Comment by ThorstenHans** [comment]
Will add it once the kids are in bed 🤪

**Review by fibonacci1729 — APPROVED** [review]
LGTM, thanks!

**Review by radu-matei — APPROVED** [review]
🎉 
Yay, thanks, @ThorstenHans!

LGTM!

**Pull request merged**
