### PR TITLE
Enable loading pre-pulled OCI artifact

### LINKED ISSUE #1858: Add ability to load OCI with pre-fetch artifacts
### Background

This issue in runwasi https://github.com/containerd/runwasi/issues/108 and the approach outlined in https://docs.google.com/document/d/11shgC3l6gplBjWF1VJCWvN_9do51otscAm0hBDGSSAc.  Also the changes proposed in https://github.com/fermyon/spin/issues/1857

### Proposed changes
In kubernetes based environment, the OCI artifacts might be already pre-pulled but the OCI client requires pulling them:

https://github.com/fermyon/spin/blob/362c75d98e3ac2cb1b760b661fbcb18f0eced118/crates/oci/src/loader.rs#L25-L29

It would be nice to have a function similiar to `let app = spin_loader::from_file(PathBuf::from("/spin.toml"), Some(working_dir.clone())).await.context("unable to find app file")?;`

but for `spin.json` that OCI artifacts use.

I've prototyped this working with this [change](https://github.com/fermyon/spin/compare/main...jsturtevant:spin:spin-oci) used in https://github.com/deislabs/containerd-wasm-shims/pull/164. But there might be better ways to approach it.

### PR DESCRIPTION
**Pull request by jsturtevant**
fixes #1858

### CODE REVIEW

**Review by itowlson — APPROVED** [review]

**Comment by itowlson** [comment]
Kia ora @jsturtevant, could you run `cargo fmt` and `cargo clippy` over this please?  We have those as gates in the CI.

**Comment by jsturtevant** [comment]
> Kia ora @jsturtevant, could you run `cargo fmt` and `cargo clippy` over this please? We have those as gates in the CI.

updated

**Review by vdice — APPROVED** [review]
LGTM, thank you @jsturtevant.

One last item, sorry.  Can you [GPG-sign the commit](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification) when convenient?

**Comment by jsturtevant** [comment]
> One last item, sorry. Can you [GPG-sign the commit](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification) when convenient?

np, should be updated. you actual helped me find a mis-configuraiotn in the linux dev set up that was causing it to not fully singing the commits 👍

**Pull request merged**
