### PR TITLE
Request ID

### PR DESCRIPTION
**Pull request by itowlson**
This is a possible approach to #2146 but I feel kinda queasy using an environment variable instead of an API but maybe that's just me

### CODE REVIEW

**Comment by karthik2804** [comment]
Would this be needed once we have wasi-observe and otel?

**Comment by itowlson** [comment]
@karthik2804 on that I was guided by https://github.com/fermyon/spin/issues/2146#issuecomment-2000217985 but for sure I do not know enough either way

**Comment by radu-matei** [comment]
Could this (also?) be a Spin variable?

**Comment by lann** [comment]
I think this may in fact be best served via wasi-observe. Distributed traces are typically keyed off of a trace ID which is either passed in via e.g. [W3C Trace Context](https://www.w3.org/TR/trace-context/) or generated by the server (if it is the first hop in the traced system). That trace ID could be emitted with logs and - if necessary - exposed to the guest via a wasi-observe import.

**Pull request closed without merging**
